-- Add category column to products for data plan categorization
ALTER TABLE products ADD COLUMN IF NOT EXISTS category text;

-- Seed categorized data plans for each network
-- MTN
INSERT INTO products (service, name, price, network, category, description) VALUES
  ('data', 'MTN 1GB SME', 300, 'MTN', 'SME', '1GB SME Data - 30 days'),
  ('data', 'MTN 2GB SME', 600, 'MTN', 'SME', '2GB SME Data - 30 days'),
  ('data', 'MTN 5GB SME', 1450, 'MTN', 'SME', '5GB SME Data - 30 days'),
  ('data', 'MTN 10GB SME', 2900, 'MTN', 'SME', '10GB SME Data - 30 days'),
  ('data', 'MTN 1GB Corporate', 350, 'MTN', 'Corporate', '1GB Corporate Data - 30 days'),
  ('data', 'MTN 2GB Corporate', 700, 'MTN', 'Corporate', '2GB Corporate Data - 30 days'),
  ('data', 'MTN 5GB Corporate', 1750, 'MTN', 'Corporate', '5GB Corporate Data - 30 days'),
  ('data', 'MTN 1GB Gifting', 320, 'MTN', 'Gifting', '1GB Gifting Data - 30 days'),
  ('data', 'MTN 2GB Gifting', 640, 'MTN', 'Gifting', '2GB Gifting Data - 30 days'),
  ('data', 'MTN 5GB Gifting', 1500, 'MTN', 'Gifting', '5GB Gifting Data - 30 days'),
  ('data', 'MTN 1GB Direct', 350, 'MTN', 'Direct', '1GB Direct Data - 30 days'),
  ('data', 'MTN 2GB Direct', 720, 'MTN', 'Direct', '2GB Direct Data - 30 days'),
  ('data', 'MTN 5GB Direct', 1500, 'MTN', 'Direct', '5GB Direct Data - 30 days'),
  ('data', 'MTN 10GB Direct', 4500, 'MTN', 'Direct', '10GB Direct Data - 30 days'),
  ('data', 'GLO 1GB SME', 300, 'GLO', 'SME', '1GB SME Data - 30 days'),
  ('data', 'GLO 2GB SME', 600, 'GLO', 'SME', '2GB SME Data - 30 days'),
  ('data', 'GLO 5GB SME', 1450, 'GLO', 'SME', '5GB SME Data - 30 days'),
  ('data', 'GLO 1GB Corporate', 350, 'GLO', 'Corporate', '1GB Corporate Data - 30 days'),
  ('data', 'GLO 2GB Corporate', 700, 'GLO', 'Corporate', '2GB Corporate Data - 30 days'),
  ('data', 'GLO 5GB Corporate', 1750, 'GLO', 'Corporate', '5GB Corporate Data - 30 days'),
  ('data', 'GLO 1GB Gifting', 320, 'GLO', 'Gifting', '1GB Gifting Data - 30 days'),
  ('data', 'GLO 2GB Gifting', 640, 'GLO', 'Gifting', '2GB Gifting Data - 30 days'),
  ('data', 'GLO 1GB Direct', 350, 'GLO', 'Direct', '1GB Direct Data - 30 days'),
  ('data', 'GLO 2GB Direct', 720, 'GLO', 'Direct', '2GB Direct Data - 30 days'),
  ('data', 'GLO 5GB Direct', 1500, 'GLO', 'Direct', '5GB Direct Data - 30 days'),
  ('data', 'AIRTEL 1GB SME', 300, 'AIRTEL', 'SME', '1GB SME Data - 30 days'),
  ('data', 'AIRTEL 2GB SME', 600, 'AIRTEL', 'SME', '2GB SME Data - 30 days'),
  ('data', 'AIRTEL 5GB SME', 1450, 'AIRTEL', 'SME', '5GB SME Data - 30 days'),
  ('data', 'AIRTEL 1GB Corporate', 350, 'AIRTEL', 'Corporate', '1GB Corporate Data - 30 days'),
  ('data', 'AIRTEL 2GB Corporate', 700, 'AIRTEL', 'Corporate', '2GB Corporate Data - 30 days'),
  ('data', 'AIRTEL 5GB Corporate', 1750, 'AIRTEL', 'Corporate', '5GB Corporate Data - 30 days'),
  ('data', 'AIRTEL 1GB Gifting', 320, 'AIRTEL', 'Gifting', '1GB Gifting Data - 30 days'),
  ('data', 'AIRTEL 2GB Gifting', 640, 'AIRTEL', 'Gifting', '2GB Gifting Data - 30 days'),
  ('data', 'AIRTEL 1GB Direct', 350, 'AIRTEL', 'Direct', '1GB Direct Data - 30 days'),
  ('data', 'AIRTEL 2GB Direct', 720, 'AIRTEL', 'Direct', '2GB Direct Data - 30 days'),
  ('data', 'AIRTEL 5GB Direct', 1500, 'AIRTEL', 'Direct', '5GB Direct Data - 30 days'),
  ('data', '9MOBILE 1GB SME', 300, '9MOBILE', 'SME', '1GB SME Data - 30 days'),
  ('data', '9MOBILE 2GB SME', 600, '9MOBILE', 'SME', '2GB SME Data - 30 days'),
  ('data', '9MOBILE 5GB SME', 1450, '9MOBILE', 'SME', '5GB SME Data - 30 days'),
  ('data', '9MOBILE 1GB Corporate', 350, '9MOBILE', 'Corporate', '1GB Corporate Data - 30 days'),
  ('data', '9MOBILE 2GB Corporate', 700, '9MOBILE', 'Corporate', '2GB Corporate Data - 30 days'),
  ('data', '9MOBILE 1GB Gifting', 320, '9MOBILE', 'Gifting', '1GB Gifting Data - 30 days'),
  ('data', '9MOBILE 2GB Gifting', 640, '9MOBILE', 'Gifting', '2GB Gifting Data - 30 days'),
  ('data', '9MOBILE 1GB Direct', 350, '9MOBILE', 'Direct', '1GB Direct Data - 30 days'),
  ('data', '9MOBILE 2GB Direct', 720, '9MOBILE', 'Direct', '2GB Direct Data - 30 days'),
  ('data', '9MOBILE 5GB Direct', 1500, '9MOBILE', 'Direct', '5GB Direct Data - 30 days')
ON CONFLICT DO NOTHING;
